[ananke]
show_recent_posts = true # show recent posts on the homepage

[ananke.social]
icon_path = "ananke/socials/%s.svg"

[ananke.social.follow]
new_window_icon = false # show a little "opens in new window" icon next to the link
# add networks to this list in your local config to enable them, remove them to disable them.
# networks = [
#   "facebook",
#   "bluesky",
#   "linkedin"
# ]

[ananke.social.share]
icons = true # show icons for each share link
sharetext = true # show the share text
# add networks to this list in your local config to enable them, remove them to disable them.
# networks = [
#   "email",
#   "facebook",
#   "bluesky",
#   "linkedin"
# ]

# social media network setups
[ananke.social.networks.bluesky]
color = "#1185fe" 
icon = "bluesky" # font awesome brand icon name
label = "Bluesky" 
link = "https://bsky.app/intent/compose" 
profile = "https://bsky.app/profile/%s" 
slug = "bluesky" 
[ananke.social.networks.bluesky.particles]
text = "permalink"

[ananke.social.networks.email]
icon = "envelope" # font awesome free icon name
label = "Email" 
link = "mailto:" 
profile = false 
slug = "email" 
[ananke.social.networks.email.particles]
body = "permalink"
subject = "title"

[ananke.social.networks.facebook]
color = "#3b5998" 
icon = "facebook" # font awesome brand icon name
label = "Facebook" 
link = "https://facebook.com/sharer/sharer.php" 
profile = "https://www.facebook.com/%s" 
slug = "facebook" 
[ananke.social.networks.facebook.particles]
u = "permalink"

[ananke.social.networks.github]
color = "#6cc644" 
icon = "github" # font awesome brand icon name
label = "GitHub" 
profile = "https://github.com/%s/" 
slug = "github" 

[ananke.social.networks.gitlab]
color = "#FC6D26" 
icon = "gitlab" # font awesome brand icon name
label = "GitLab" 
profile = "https://gitlab.com/%s/" 
slug = "gitlab" 

[ananke.social.networks.hackernews]
color = "#ff4000" 
icon = "hacker-news" # font awesome brand icon name
label = "Hacker News" 
link = "https://news.ycombinator.com/submitlink" 
profile = "https://news.ycombinator.com/user?id=%s" 
slug = "hackernews" 
[ananke.social.networks.hackernews.particles]
t = "description"
u = "permalink"

[ananke.social.networks.instagram]
color = "#e1306c" 
icon = "instagram" # font awesome brand icon name
label = "Instagram" 
profile = "https://www.instagram.com/%s/" 
slug = "instagram" 

[ananke.social.networks.keybase]
color = "#3d76ff" 
icon = "keybase" # font awesome brand icon name
label = "Keybase" 
profile = "https://keybase.io/%s" 
slug = "keybase" 

[ananke.social.networks.linkedin]
color = "#0077b5" 
icon = "linkedin" # font awesome brand icon name
label = "LinkedIn" 
link = "https://www.linkedin.com/shareArticle" 
profile = "http://linkedin.com/in/%s" 
slug = "linkedin" 
[ananke.social.networks.linkedin.particles]
params = "mini=true"
source = "permalink"
summary = "description"
title = "title"
url = "permalink"

[ananke.social.networks.medium]
color = "#0077b5" 
icon = "medium" # font awesome brand icon name
label = "Medium" 
profile = "https://medium.com/@%s/" 
slug = "medium" 

[ananke.social.networks.mastodon]
color = "#6364FF" 
icon = "mastodon" # font awesome brand icon name
label = "Mastodon" 
profile = "" 
slug = "mastodon" 

[ananke.social.networks.pinterest]
color = "#e60023" 
icon = "pinterest" # font awesome brand icon name
label = "Pinterest" 
link = "https://pinterest.com/pin/create/button/" 
profile = "https://www.pinterest.com/%s/" 
slug = "pinterest" 
[ananke.social.networks.pinterest.particles]
description = "description"
media = "permalink"
url = "permalink"

[ananke.social.networks.reddit]
color = "#ff4500" 
icon = "reddit" # font awesome brand icon name
label = "Reddit" 
link = "https://reddit.com/submit/" 
profile = "https://www.reddit.com/user/%s/" 
slug = "reddit" 
[ananke.social.networks.reddit.particles]
params = "resubmit=true"
title = "title"
url = "permalink"

[ananke.social.networks.rss]
color = "#ff6f1a" 
icon = "rss" # font awesome free icon name
label = "RSS" 
profile = "" 
slug = "rss" 

[ananke.social.networks.slack]
color = "#E01E5A" 
icon = "slack" # font awesome brand icon name
label = "Slack" 
profile = "" 
slug = "slack" 

[ananke.social.networks.stackoverflow]
color = "#f48024" 
icon = "stack-overflow" # font awesome brand icon name
label = "Stack Overflow" 
profile = "https://stackoverflow.com/users/%s" 
slug = "stackoverflow" 

[ananke.social.networks.telegram]
color = "#0088cc" 
icon = "telegram" # font awesome brand icon name
label = "Telegram" 
link = "https://telegram.me/share/url" 
profile = "https://t.me/%s" 
slug = "telegram" 
[ananke.social.networks.telegram.particles]
text = "description"
url = "permalink"

[ananke.social.networks.tiktok]
color = "#fe2c55" 
icon = "tiktok" # font awesome brand icon name
label = "TikTok" 
profile = "https://www.tiktok.com/@%s" 
slug = "tiktok" 

[ananke.social.networks.tumblr]
color = "#35465c" 
icon = "tumblr" # font awesome brand icon name
label = "Tumblr" 
link = "https://www.tumblr.com/widgets/share/tool" 
profile = "https://www.tumblr.com/blog/%s" 
slug = "tumblr" 
[ananke.social.networks.tumblr.particles]
canonicalUrl = "permalink"
caption = "description"
content = "description"
params = "posttype=link"
shareSource = "source"
title = "title"

[ananke.social.networks.twitter]
color = "#1da1f2" 
icon = "twitter" # font awesome brand icon name
label = "Twitter" 
link = "https://twitter.com/intent/tweet/" 
profile = "https://twitter.com/%s" 
slug = "twitter" 
[ananke.social.networks.twitter.particles]
text = "description"
url = "permalink"

[ananke.social.networks.whatsapp]
color = "#25d366" 
icon = "whatsapp" # font awesome brand icon name
label = "WhatsApp" 
link = "whatsapp://send" 
linkintext = true 
profile = false 
slug = "whatsapp" 
[ananke.social.networks.whatsapp.particles]
text = "description"

[ananke.social.networks.xing]
color = "#026466" 
icon = "xing" # font awesome brand icon name
label = "Xing" 
link = "https://www.xing.com/app/user" 
profile = "https://www.xing.com/profile/%s" 
separator = ";" 
slug = "xing" 
[ananke.social.networks.xing.particles]
params = "op=share"
title = "title"
url = "permalink"

[ananke.social.networks.x-twitter]
color = "#000000" 
icon = "x-twitter" # font awesome brand icon name
label = "X" 
link = "https://twitter.com/intent/tweet/" 
profile = "https://x.com/%s" 
slug = "x-twitter" 
[ananke.social.networks.x-twitter.particles]
text = "description"
url = "permalink"

[ananke.social.networks.youtube]
color = "#cd201f" 
icon = "youtube" # font awesome brand icon name
label = "YouTube" 
profile = "https://www.youtube.com/@%s" 
slug = "youtube"
